CITNOVA/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import urls as accountsUrls
from solicitudes import urls as solicitudesUrls
from presupuesto import urls as presupuestoUrls
#Libreria para importar imagenes
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include(accountsUrls, namespace="accounts")),
	url(r'^', include(solicitudesUrls, namespace="solicitudes")),
    url(r'^', include(presupuestoUrls, namespace="presupuesto")),
    #Direccion para buscar imagenes
    url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs ={'document_root':settings.MEDIA_ROOT}
    ),
]

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout

urlpatterns = [
	#urls de empleados
	url(r'^accounts/director/actualizar/(?P<pk>\d+)/$', views.UpdateViewDirector.as_view(), name="UpdateViewDirector"),
	url(r'^accounts/director/nuevo/$',views.CreateViewDirector.as_view(), name='CreateViewDirector'),
	url(r'^accounts/directores/$',views.ListViewDirectores.as_view(), name='ListViewDirectores'),

	#urls de empleados
	url(r'^accounts/empleado/desactivar/(?P<pk>\d+)/$', views.DesactivateViewUser.as_view(), name="DesactivateViewUser"),
	url(r'^accounts/empleado/actualizar/(?P<pk>\d+)/$', views.UpdateViewEmpleado.as_view(), name="UpdateViewEmpleado"),
	url(r'^accounts/empleado/nuevo/$',views.CreateViewEmpleado.as_view(), name='CreateViewEmpleado'),
	url(r'^accounts/empleados/$',views.ListViewEmpleados.as_view(), name='ListViewEmpleados'),

	#urls de proveedores
	url(r'^accounts/proveedor/actualizar/(?P<pk>\d+)/$', views.UpdateViewProveedor.as_view(), name="UpdateViewProveedor"),
	url(r'^accounts/proveedor/nuevo/$',views.CreateViewProveedor.as_view(), name='CreateViewProveedor'),
	url(r'^accounts/proveedores/$',views.ListViewProveedores.as_view(), name='ListViewProveedores'),

	#urls de bancos
	url(r'^accounts/bancos/actualizar/(?P<pk>\d+)$',views.UpdateViewBanco.as_view(), name='UpdateViewBanco'),
	url(r'^accounts/bancos/eliminar/(?P<pk>\d+)$',views.DeleteViewBanco.as_view(), name='DeleteViewBanco'),
	url(r'^accounts/bancos/nuevo/$',views.CreateViewBanco.as_view(), name='CreateViewBanco'),	
	url(r'^accounts/bancos/$',views.ListViewBancos.as_view(), name='ListViewBancos'),
	
	#urls de departamentos
	url(r'^accounts/departamentos/actualizar/(?P<pk>\d+)$',views.UpdateViewDepartamento.as_view(), name='UpdateViewDepartamento'),
	url(r'^accounts/departamentos/eliminar/(?P<pk>\d+)$',views.DeleteViewDepartamento.as_view(), name='DeleteViewDepartamento'),
	url(r'^accounts/departamentos/nuevo/$',views.CreateViewDepartamento.as_view(), name='CreateViewDepartamento'),	
	url(r'^accounts/departamentos/$',views.ListViewDepartamentos.as_view(), name='ListViewDepartamentos'),

	#url de perfil
	url(r'^accounts/profile/$',views.profile.as_view(), name='profile'),
	
	#url de login y logout
	url(r'^solicitudes/login/$', login,name="login"),
	url(r'^logout/$', logout, name="logout"),
]

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

#Formularios de empleado
class UserEmpleadoCreateForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email', 'departamento',)

class PerfilEmpleadoCreateForm(forms.ModelForm):
	class Meta:
		model = Perfil
		fields = ('grado_profesional', 'puesto', 'teléfono', 'banco', 'cuenta_bancaria', 'CLABE')

#formularios de director
class UserDirectorCreateForm(forms.ModelForm):
	password = forms.CharField(label='Password',widget=forms.PasswordInput)
	password2 = forms.CharField(label='Repite tu password',widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('username','first_name', 'last_name', 'email', 'departamento')
	
	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password'] != cd['password2']:
			raise forms.ValidationError('Los passwords no coicinden')
		return cd['password2']

	def clean_username(self):
	    username = self.cleaned_data['username']
	    try:
	        user = User.objects.exclude(pk=self.instance.pk).get(username=username)
	    except User.DoesNotExist:
	        return username
	    raise forms.ValidationError(u'Username "%s" is already in use.' % username)

class UserDirectorEditForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email', 'departamento')

class PerfilDirectorCreateForm(forms.ModelForm):
	class Meta:
		model = Perfil
		fields = ('grado_profesional', 'teléfono', 'banco', 'cuenta_bancaria', 'CLABE')




#Formularios de proveedor
class UserProveedorCreateForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email')

class PerfilProveedorCreateForm(forms.ModelForm):
	class Meta:
		model = Perfil
		fields = ('grado_profesional', 'teléfono', 'banco', 'cuenta_bancaria', 'CLABE')

class ExpedienteProveedorCreateForm(forms.ModelForm):
	class Meta:
		model = Expediente
#		fields = ('tipo', 'RFC', 'IFE')
		fields = ('tipo', 'Identifación_oficial', 'RFC', 'Comprobante_de_domicilio', 'Registro_de_padrón_de_proveedores', 'Tres_cotizaciones', 'Opinión_de_cumplimiento', 'Acta_constitutiva', 'Representación_legal')

class UserDesactivateForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('is_active',)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.contrib.auth.models import User
from .forms import *
from django.db.models import Count
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

#Lista de empleados
class ListViewEmpleados(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "accounts/ListViewEmpleados.html"

		empleados = User.objects.filter(departamento=request.user.departamento, is_active=True).order_by('username')

		context = {
			'empleados': empleados,
		}
		return render(request,template_name,context)

#Lista de proveedores
class ListViewProveedores(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "accounts/ListViewProveedores.html"

		proveedores = User.objects.filter(is_staff=False, is_active=True, username__startswith='PROV').order_by('username')

		context = {
			'proveedores': proveedores
		}
		return render(request,template_name,context)

#Creación de un empleado
class CreateViewEmpleado(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "accounts/createEmpleado.html"
		
		UserEmpleadoForm = UserEmpleadoCreateForm()
		PerfilEmpleadoForm = PerfilEmpleadoCreateForm()
		
		context = {
			'UserEmpleadoForm': UserEmpleadoForm,
			'PerfilEmpleadoForm': PerfilEmpleadoForm,
		}
		return render(request,template_name,context)
	def post(self,request):
		template_name = "accounts/createEmpleado.html"

		users = User.objects.filter(is_staff=False).count()
		userActual = users + 1

		NuevoUserForm = UserEmpleadoCreateForm(request.POST)
		NuevoPerfilForm = PerfilEmpleadoCreateForm(request.POST)
		
		if NuevoUserForm.is_valid(): 
			NuevoUser = NuevoUserForm.save(commit=False)
			NuevoUser.username = 'EMPL' + str(NuevoUser.first_name[0].upper()) + str(NuevoUser.last_name[0].upper()) + str(userActual)
			NuevoUser.save()

		if NuevoPerfilForm.is_valid():
			NuevoPerfil = NuevoPerfilForm.save(commit=False)
			NuevoPerfil.user = NuevoUser
			NuevoPerfil.save()
		return redirect("accounts:ListViewEmpleados")

#Creación de un Proveedor
class CreateViewProveedor(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "accounts/createProveedor.html"
		
		UserProveedorForm = UserProveedorCreateForm()
		PerfilProveedorForm = PerfilProveedorCreateForm()
		ExpedienteProveedorForm = ExpedienteProveedorCreateForm()
		
		context = {
			'UserProveedorForm': UserProveedorForm,
			'PerfilProveedorForm': PerfilProveedorForm,
			'ExpedienteProveedorForm': ExpedienteProveedorForm,
		}
		return render(request,template_name,context)
	def post(self,request):
		template_name = "accounts/createProveedor.html"

		users = User.objects.filter(is_staff=False).count()
		userActual = users + 1

		NuevoUserForm = UserProveedorCreateForm(request.POST)		
		NuevoPerfilForm = PerfilProveedorCreateForm(request.POST)
		NuevoExpedienteForm = ExpedienteProveedorCreateForm(request.POST, request.FILES)

		if NuevoUserForm.is_valid(): 
			NuevoUser = NuevoUserForm.save(commit=False)
			NuevoUser.username = 'PROV' + str(NuevoUser.first_name[0].upper()) + str(NuevoUser.last_name[0].upper()) + str(userActual)
			NuevoUser.save()


		if NuevoPerfilForm.is_valid():
			NuevoPerfil = NuevoPerfilForm.save(commit=False)
			NuevoPerfil.user = NuevoUser
			NuevoPerfil.save()

		if NuevoExpedienteForm.is_valid():
			NuevoExpediente = NuevoExpedienteForm.save(commit=False)
			NuevoExpediente.perfil = NuevoPerfil
			NuevoExpediente.save()
			
		return redirect("accounts:ListViewProveedores")

#Edición de un empleado
class UpdateViewEmpleado(View):
	@method_decorator(login_required)
	def get(self, request, pk):
		template_name = "accounts/updateEmpleado.html"
		user = get_object_or_404(User, pk=pk)
		perfil = Perfil.objects.get(user=user)

		EdicionEmpleadoForm=UserEmpleadoCreateForm(instance=user)
		EdicionPerfilForm=PerfilEmpleadoCreateForm(instance=perfil)
	
		context = {
			'EdicionEmpleadoForm': EdicionEmpleadoForm,
			'EdicionPerfilForm': EdicionPerfilForm,
		}
		return render(request, template_name, context)
	def post(self,request, pk):
		template_name = "accounts/updateEmpleado.html"
		user = get_object_or_404(User, pk=pk)
		perfil = Perfil.objects.get(user=user)

		EdicionEmpleadoForm=UserEmpleadoCreateForm(instance=user, data=request.POST)
		EdicionPerfilForm=PerfilEmpleadoCreateForm(instance=perfil, data=request.POST)

		if EdicionEmpleadoForm.is_valid:
			EdicionEmpleadoForm.save()

		if EdicionPerfilForm.is_valid:
			EdicionPerfilForm.save()

			messages.success(request, "Se han gaurdado los cambios correctamente")
		return redirect("accounts:UpdateViewEmpleado", pk=user.pk)

#Edición de un proveedor
class UpdateViewProveedor(View):
	@method_decorator(login_required)
	def get(self, request, pk):
		template_name = "accounts/updateProveedor.html"
		user = get_object_or_404(User, pk=pk)
		perfil = Perfil.objects.get(user=user)
		expediente = Expediente.objects.get(perfil=perfil)

		EdicionProveedorForm=UserProveedorCreateForm(instance=user)
		EdicionPerfilForm=PerfilProveedorCreateForm(instance=perfil)
		EdicionExpedienteForm=ExpedienteProveedorCreateForm(instance=expediente)
		context = {
			'expediente': expediente,
			'EdicionProveedorForm': EdicionProveedorForm,
			'EdicionPerfilForm': EdicionPerfilForm,
			'EdicionExpedienteForm': EdicionExpedienteForm
		}
		return render(request, template_name, context)
	def post(self,request, pk):
		template_name = "accounts/updateProveedor.html"
		user = get_object_or_404(User, pk=pk)
		perfil = Perfil.objects.get(user=user)
		expediente = Expediente.objects.get(perfil=perfil)
		
		EdicionProveedorForm=UserProveedorCreateForm(instance=user, data=request.POST)
		EdicionPerfilForm=PerfilProveedorCreateForm(instance=perfil, data=request.POST)
		EdicionExpedienteForm=ExpedienteProveedorCreateForm(instance=expediente, data=request.POST, files=request.FILES)
		
		if EdicionProveedorForm.is_valid:
			EdicionProveedorForm.save()

		if EdicionPerfilForm.is_valid:
			EdicionPerfilForm.save()

		if EdicionExpedienteForm.is_valid():
			EdicionExpedienteForm.save()

			messages.success(request, "Se han gaurdado los cambios correctamente")

		return redirect("accounts:UpdateViewProveedor", pk=user.pk)

#Desactivación de un empleado o proveedor
class DesactivateViewUser(View):
	@method_decorator(login_required)
	def get(self, request, pk):
		template_name = "accounts/desactivateUser.html"
		user = get_object_or_404(User, pk=pk)
		perfil = Perfil.objects.get(user=user)
		expediente = Expediente.objects.filter(perfil=perfil)

		DesactivaUserForm = UserDesactivateForm(instance=user)
	
		context = {
			'user': user,
			'perfil': perfil,
			'DesactivaUserForm': DesactivaUserForm,
		}
		return render(request, template_name, context)
	def post(self,request, pk):
		template_name = "accounts/desactivateUser.html"
		user = get_object_or_404(User, pk=pk)
		perfil = Perfil.objects.get(user=user)
		expediente = Expediente.objects.filter(perfil=perfil)

		DesactivaUserForm = UserDesactivateForm(instance=user, data=request.POST)
	
		if DesactivaUserForm.is_valid:
			DesactivaUserForm.save()

		if request.user.username == "administrador":
			return redirect("accounts:ListViewDirectores")
		else:
			if expediente.exists():
				return redirect("accounts:ListViewProveedores")
			else:
				return redirect("accounts:ListViewEmpleados")

#Lista de bancos
class ListViewBancos(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "accounts/listBancos.html"
		bancos = Banco.objects.all()
		context = {
			'bancos': bancos
		}
		return render(request,template_name, context)

#Creación de bancos
class CreateViewBanco(CreateView):
	model = Banco
	success_url = reverse_lazy('accounts:ListViewBancos')
	fields = ['nombre',]

#Edición de bancos
class UpdateViewBanco(UpdateView):
	model = Banco
	success_url = reverse_lazy('accounts:ListViewBancos')
	fields = ['nombre',]

#Borrado de Bancos
class DeleteViewBanco(DeleteView):
	model = Banco
	success_url = reverse_lazy('accounts:ListViewBancos')

#Perfil de usuario autenticado
class profile(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "accounts/profile.html"
		perfil = Perfil.objects.get(user=request.user)
		
		context = {
			'perfil': perfil
		}		
		return render(request,template_name, context)

#Lista de bancos
class ListViewDepartamentos(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "accounts/listDepartamentos.html"
		departamentos = Departamento.objects.all()
		context = {
			'departamentos': departamentos
		}
		return render(request,template_name, context)

#Creación de Departamentos
class CreateViewDepartamento(CreateView):
	model = Departamento
	success_url = reverse_lazy('accounts:ListViewDepartamentos')
	fields = ['nombre','codigo',]

#Edicion de Departamentos
class UpdateViewDepartamento(UpdateView):
	model = Departamento
	success_url = reverse_lazy('accounts:ListViewDepartamentos')
	fields = ['nombre','codigo',]

#Borrado de Departamentos
class DeleteViewDepartamento(DeleteView):
	model = Departamento
	success_url = reverse_lazy('accounts:ListViewDepartamentos')

#Lista de directores
class ListViewDirectores(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "accounts/ListViewDirectores.html"

		users = User.objects.filter(is_active=True).order_by('username')

		directores = []
		for user in users:
			try:
				perfil = Perfil.objects.get(user=user)
				if perfil.puesto == "Director":		
					directores.append({'user': user, 'perfil':Perfil.objects.filter(user=user)})
			except Exception as e:
				directores = []
		print()
		context = {

accounts/templates/accounts/ListViewDirectores.html
{%extends 'baseUser.html'%}

{%block content%}

	<h4 class="text-center">Catalogo del directores</h4>

	<div class="table-responsive">
		<table class="table table-striped table-bordered">
			<thead>
				<th>Nombre</th>
				<th colspan="2">Acciones</th>
			</thead>
			<tbody>

			{%for director in directores%}
	
				<tr>
					<td>{{director.user.first_name}} {{director.user.last_name}}</td>
					<td><a href="{%url 'accounts:UpdateViewDirector' director.user.pk%}">Actualizar</a></td>
					<td><a href="{%url 'accounts:DesactivateViewUser' director.user.pk%}">Eliminar</a></td>
				</tr>

			{%empty%}
	
				<tr>
					<td colspan="3"> Lista de directores vacia</td>
				</tr>
	
			{%endfor%}
			
			</tbody>
		</table>
	</div>

{%endblock content%}

accounts/templates/accounts/ListViewProveedores.html
{%extends 'baseUser.html'%}

{%block content%}

	<h4 class="text-center">Catalogo de proveedores</h4>

	<div class="table-responsive">
		<table class="table table table-striped table-bordered">
			<thead>
				<th>Nombre</th>
				<th colspan="2">Acciones</th>
			</thead>
			<tbody>
			
			{%for proveedor in proveedores%}

				<tr>
					<td>{{proveedor.first_name}} {{proveedor.last_name}}</td>
					<td><a href="{%url 'accounts:UpdateViewProveedor' proveedor.pk%}"><p class="text-center">Actualizar</p></a>
					</td>
					<td><a href="{%url 'accounts:DesactivateViewUser' proveedor.pk%}">Eliminar</a></td>
				</tr>

			{%empty%}

				<tr>
					<td colspan="3"> Lista de proveedores vacia</td>
				</tr>

			{%endfor%}

			</tbody>
		</table>
	</div>

{%endblock content%}

accounts/templates/accounts/banco_confirm_delete.html
{%extends 'baseUser.html'%}

{%block content%}

	<div class="row justify-content-center text-center">
		<div class="col-xs-12">
	
		<form method="post">
			<p>¿Estas seguro de querer borrar el banco <em>{{object}}</em>?</p>

			{%csrf_token%}
			
			<input class="" type="submit" value="Si">
	
			<a href="{%url 'accounts:ListViewBancos'%}"><input class="" type="button" value="Cancelar"></a>
		</form>
		</div>
	</div>
	
{%endblock content%}

accounts/templates/accounts/createDirector.html
{%extends 'baseUser.html'%}

{% load bootstrap %}

{%block content%}

	<h4>Registro de nuevo director</h4>



	<form action="." method="post">
		{%csrf_token%}
		{{UserDirectorForm | bootstrap}}
		{{PerfilDirectorForm | bootstrap}}
		<input type="submit" value="Crear Usuario">
	</form>
	
	<div>
		
		{% if messages %}
		
			<ul class="messages">
    	
    		{% for message in messages %}
    	
	    	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    	
	    	{% endfor %}
		
			</ul>
		
		{% endif %}

	</div>
{%endblock content%}

accounts/templates/accounts/createEmpleado.html
{%extends 'baseUser.html'%}

{% load bootstrap %}

{%block content%}

	<h4>Registro de nuevo empleado</h4>
	<form action="." method="post">
		{%csrf_token%}
		{{UserEmpleadoForm | bootstrap}}
		{{PerfilEmpleadoForm | bootstrap}}
		<input type="submit" value="Crear Usuario">
	</form>
	
{%endblock content%}

accounts/templates/accounts/createProveedor.html
{%extends 'baseUser.html'%}

{% load bootstrap %}

{%block content%}

	<h4>Registro de nuevo proveedor</h4>
	<form action="." method="post" enctype="multipart/form-data">
			{%csrf_token%}
			{{UserProveedorForm | bootstrap}}
			{{PerfilProveedorForm | bootstrap}}
			{{ExpedienteProveedorForm | bootstrap}}			
			<input type="submit" value="Registrar proveedor">
	</form>

{%endblock content%}

accounts/templates/accounts/departamento_confirm_delete.html
{%extends 'baseUser.html'%}

{%block content%}

	<div class="row justify-content-center text-center">
		<div class="col-xs-12">
	
		<form method="post">
			<p>¿Estas seguro de querer borrar la <em>{{object}}</em>?</p>

			{%csrf_token%}
			
			<input class="" type="submit" value="Si">
	
			<a href="{%url 'accounts:ListViewDepartamentos'%}"><input class="" type="button" value="Cancelar"></a>
		</form>
		</div>
	</div>
	
{%endblock content%}

accounts/templates/accounts/departamento_form.html
{%extends 'baseUser.html'%}

{% load bootstrap %}

{%block content%}

	{%if object%}
	<h3>Edita la información dirección <i>{{object}}</i></h3>
	{%else%}
	<h3>Registra el nombre de una dirección</h3>
	{%endif%}

	<form method="post" enctype="multipart/form-data">
		{%csrf_token%}
		{{form | bootstrap}}
		<input type="submit" value="{%if object%}Guardar cambios{%else%}Crear{%endif%}">
		<a href="{%url 'accounts:ListViewDepartamentos'%}"><input class="" type="button" value="Cancelar"></a>
	</form>

{%endblock content%}

accounts/templates/accounts/desactivateUser.html
{%extends 'baseUser.html'%}


{% load bootstrap %}

{%block content%}

	<h4>Eliminar empleado</h4>

	<p>Nombre: {{user.first_name}} {{user.last_name}}</p>
	<p>Esta aplicación tiene información de interés histórico, por lo que la información del personal no puede ser borrada, pero al desmarcar la opción de <strong>Activo</strong>, ya no aparecerá en el catalogo actual.</p>
	
	<form action="." method="post">
		{%csrf_token%}
		{{DesactivaUserForm | bootstrap}}
		<input type="submit" value="Desactivar">
	</form>

{%endblock content%}

accounts/templates/accounts/listBancos.html
{%extends 'baseUser.html'%}

{%block content%}

	<h4 class="text-center">Catalogo de bancos</h4>

	<div class="table-responsive">
		<table  class="table">
			<thead>
				<th>Nombre</th>
				<th colspan="2">Acciones</th>
			</thead>
			<tbody>

			{%for banco in bancos%}

			<tr>
				<td>{{banco.nombre}}</td>
				<td><a href="{%url 'accounts:UpdateViewBanco' banco.pk%}">Editar</a></td>
				<td><a href="{%url 'accounts:DeleteViewBanco' banco.pk%}">Borrar</a></td>
			</tr>

			{%empty%}

			<tr>
				<td colspan="3">Lista de bancos vacia</td>
			</tr>

			{%endfor%}
			
			</tbody>
		</table>
	</div>

{%endblock content%}

accounts/templates/accounts/listDepartamentos.html
{%extends 'baseUser.html'%}

{%block content%}
	
	<h4 class="text-center">Lista de direcciones</h4>

	<div class="table-responsive">
		<table class="table">
			<thead>
				<th>Nombre</th>
				<th colspan="2">Acciones</th>
			</thead>
			<tbody>
	
	{%for departamento in departamentos%}
	
				<tr>
					<td>{{departamento.nombre}}</td>
					<td><a href="{%url 'accounts:UpdateViewDepartamento' departamento.pk%}">Actualizar</a></td>
					<td><a href="{%url 'accounts:DeleteViewDepartamento' departamento.pk%}">Eliminar</a></td>
				</tr>

			{%empty%}

				<tr>
					<td colspan="3">Lista de departamentos vacia</td>
				</tr>

			{%endfor%}

			</tbody>
		</table>
	</div>

{%endblock content%}

accounts/templates/accounts/profile.html
{%extends 'baseUser.html'%}

{%block content%}

	<h2 class="text-center">Bienvenido(a)</h2>
	<h2 class="text-center">{{perfil.grado_profesional}} {{request.user.first_name}} {{request.user.last_name}}</h2>
	{%if request.user.departamento is not None%}
	<h3 class="text-center">Titular de la {{request.user.departamento}}</h3>
	{%endif%}
{%endblock content%}

accounts/templates/accounts/updateDirector.html
{%extends 'baseUser.html'%}

{% load bootstrap %}

{%block content%}

	<div>

	{% if messages %}


		<div class="messages">

			{% for message in messages %}
		
			<div {% if message.tags %} class="alert alert-success"{% endif %}>{{ message }}</div>
			
			{% endfor %}
		
		</div>

	{% endif %}

	</div>

	<h4>Actualice la información del empleado</h4>
	<form action="." method="post">
		{%csrf_token%}
		{{EdicionDirectorForm | bootstrap}}
		{{EdicionPerfilForm | bootstrap}}
		<input type="submit" value="Guardar">
	</form>

{%endblock content%}

accounts/templates/accounts/updateEmpleado.html
{%extends 'baseUser.html'%}

{% load bootstrap %}

{%block content%}

	<div>

	{% if messages %}


		<div class="messages">

			{% for message in messages %}
		
			<div {% if message.tags %} class="alert alert-success"{% endif %}>{{ message }}</div>
			
			{% endfor %}
		
		</div>

	{% endif %}

	</div>

	<h4>Actualice la información del empleado</h4>
	<form action="." method="post">
		{%csrf_token%}
		{{EdicionEmpleadoForm | bootstrap}}
		{{EdicionPerfilForm | bootstrap}}
		<input type="submit" value="Guardar">
	</form>

{%endblock content%}