CITNOVA/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import urls as accountsUrls
from solicitudes import urls as solicitudesUrls
from presupuesto import urls as presupuestoUrls
#Libreria para importar imagenes
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include(accountsUrls, namespace="accounts")),
	url(r'^', include(solicitudesUrls, namespace="solicitudes")),
    url(r'^', include(presupuestoUrls, namespace="presupuesto")),
    #Direccion para buscar imagenes
    url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs ={'document_root':settings.MEDIA_ROOT}
    ),
]

presupuesto/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	
	url(r'^programas/capitulos/partidas/meses/actualizar/ampliacion/(?P<pk>\d+)/$', views.UpdateViewMesAmpliacion.as_view(), name="UpdateViewMesAmpliacion"),
	url(r'^programas/capitulos/partidas/meses/actualizar/reduccion/(?P<pk>\d+)/$', views.UpdateViewMesReduccion.as_view(), name="UpdateViewMesReduccion"),
	url(r'^programas/capitulos/partidas/meses/actualizar/ejercido/empleado/(?P<pk>\d+)/$', views.UpdateViewMesEjercido.as_view(), name="UpdateViewMesEjercido"),
	url(r'^programas/capitulos/partidas/meses/actualizar/ejercido/proveedor/(?P<pk>\d+)/$', views.UpdateViewMesEjercido2.as_view(), name="UpdateViewMesEjercido2"),

	url(r'^programas/capitulos/partidas/meses/nuevo/(?P<pk>\d+)/$', views.CreateViewMes.as_view(), name="CreateViewMes"),
	url(r'^programas/capitulos/partidas/meses/actualizar/(?P<pk>\d+)/$', views.UpdateViewMes.as_view(), name="UpdateViewMes"),
	url(r'^programas/capitulos/partidas/meses/eliminar/(?P<pk>\d+)/$', views.DeleteViewMes.as_view(), name="DeleteViewMes"),
	url(r'^programas/capitulos/partidas/meses/(?P<pk>\d+)/$', views.ListViewMeses.as_view(), name="ListViewMeses"),

	url(r'^programas/capitulos/partidas/nuevo/(?P<pk>\d+)/$', views.CreateViewPartida.as_view(), name="CreateViewPartida"),
	url(r'^programas/capitulos/partidas/actualizar/(?P<pk>\d+)/$', views.UpdateViewPartida.as_view(), name="UpdateViewPartida"),
	url(r'^programas/capitulos/partidas/eliminar/(?P<pk>\d+)/$', views.DeleteViewPartida.as_view(), name="DeleteViewPartida"),
	url(r'^programas/capitulos/partidas/(?P<pk>\d+)/$', views.ListViewPartidas.as_view(), name="ListViewPartidas"),

	url(r'^programas/capitulos/nuevo/(?P<pk>\d+)/$', views.CreateViewCapitulo.as_view(), name="CreateViewCapitulo"),
	url(r'^programas/capitulos/actualizar/(?P<pk>\d+)/$', views.UpdateViewCapitulo.as_view(), name="UpdateViewCapitulo"),
	url(r'^programas/capitulos/eliminar/(?P<pk>\d+)/$', views.DeleteViewCapitulo.as_view(), name="DeleteViewCapitulo"),
	url(r'^programas/capitulos/(?P<pk>\d+)/$', views.ListViewCapitulos.as_view(), name="ListViewCapitulos"),
	
	url(r'^programas/nuevo/$', views.CreateViewPrograma.as_view(), name="CreateViewPrograma"),
	url(r'^programas/actualizar/(?P<pk>\d+)/$', views.UpdateViewPrograma.as_view(), name="UpdateViewPrograma"),
	url(r'^programas/eliminar/(?P<pk>\d+)/$', views.DeleteViewPrograma.as_view(), name="DeleteViewPrograma"),
	url(r'^programas/$',views.ListViewProgramas.as_view(),name='ListViewProgramas'),
]

solicitudes/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

	url(r'^solicitudes/search/$',views.SearchSolicitudes.as_view(), name='SearchSolicitudes'),

	#Urls de detalla de solicitudes 
	url(r'^solicitudes/consultar/propias/(?P<pk>\d+)/$', views.DetailViewSolicitudPropia.as_view(), name="DetailViewSolicitudPropia"),
	url(r'^solicitudes/consultar/ajenas/(?P<pk>\d+)/$', views.DetailViewSolicitudPendiente.as_view(), name="DetailViewSolicitudPendiente"),
	url(r'^solicitudes/por_mes/(?P<pk>\d+)/$', views.ListViewSolicitudesPorMes.as_view(), name="ListViewSolicitudesPorMes"),

	#Urls de creación de solicitudes
	url(r'^solicitudes/empleado/nuevo/$',views.CreateViewSolicitudEmpleado.as_view(), name='CreateViewSolicitudEmpleado'),
	url(r'^solicitudes/proveedor/nuevo/$',views.CreateViewSolicitudProveedor.as_view(), name='CreateViewSolicitudProveedor'),	
	
	#Urls de listas de solicitudes
	url(r'^solicitudes/por_pagar/$',views.ListViewSolicitudesPendientes.as_view(), name='ListViewSolicitudesPendientes'),
	url(r'^solicitudes/pagadas/$',views.ListViewSolicitudesPagadas.as_view(), name='ListViewSolicitudesPagadas'),
	url(r'^solicitudes/$',views.ListViewSolicitudesPropias.as_view(), name='ListViewSolicitudesPropias'),

]

presupuesto/forms.py
from django import forms
from .models import *
from decimal import Decimal

class MesCreateForm(forms.ModelForm):
	class Meta:
		model = Mes
		fields = ( 'mes','monto_autorizado',)

class MesEditForm(forms.ModelForm):
	class Meta:
		model = Mes
		fields = ('mes', 'monto_ampliacion','monto_reduccion', 'monto_ejercido',)

class PartidaCreateForm(forms.ModelForm):
	class Meta:
		model = Partida
		fields = ( 'codigo','descripcion',)

class CapituloCreateForm(forms.ModelForm):
	class Meta:
		model = Capitulo
		fields = ( 'codigo',)

class ModificacionForm(forms.Form):
	cantidad = forms.DecimalField(max_digits=20,decimal_places=2)

	def clean(self):
		cd = self.cleaned_data
		return cd

presupuesto/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from .models import *
from django.db.models import Sum
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .forms import *
from django.contrib import messages
from decimal import Decimal
from django.contrib import messages
import datetime
from accounts.models import Perfil
from solicitudes.forms import *
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

#Lista de programas
class ListViewProgramas(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "presupuesto/listProgramas.html"
		hoy = datetime.datetime.now()
		user = request.user
		
		if user.departamento is None:
			programas = Programa.objects.filter(año=hoy.year).order_by('nombre')
		else:
			programas = Programa.objects.filter(año=hoy.year, departamento=user.departamento).order_by('nombre')
	
		total_monto_anual_autorizado_dict = programas.aggregate(Sum('monto_anual_autorizado'))
		total_monto_anual_autorizado = total_monto_anual_autorizado_dict['monto_anual_autorizado__sum']

		total_monto_anual_ampliacion_dict = programas.aggregate(Sum('monto_anual_ampliacion'))
		total_monto_anual_ampliacion = total_monto_anual_ampliacion_dict['monto_anual_ampliacion__sum']
	
		total_monto_anual_reduccion_dict = programas.aggregate(Sum('monto_anual_reduccion'))
		total_monto_anual_reduccion = total_monto_anual_reduccion_dict['monto_anual_reduccion__sum']
	
		total_monto_anual_modificado_dict = programas.aggregate(Sum('monto_anual_modificado'))
		total_monto_anual_modificado = total_monto_anual_modificado_dict['monto_anual_modificado__sum']

		total_monto_anual_ejercido_dict = programas.aggregate(Sum('monto_anual_ejercido'))
		total_monto_anual_ejercido = total_monto_anual_ejercido_dict['monto_anual_ejercido__sum']

		total_monto_anual_por_ejercer_dict = programas.aggregate(Sum('monto_anual_por_ejercer'))
		total_monto_anual_por_ejercer = total_monto_anual_por_ejercer_dict['monto_anual_por_ejercer__sum']

		#Sumatoria del primer trimestre
		total_monto_1t_autorizado_dict = programas.aggregate(Sum('monto_1t_autorizado'))
		total_monto_1t_autorizado = total_monto_1t_autorizado_dict['monto_1t_autorizado__sum']

		total_monto_1t_ampliacion_dict = programas.aggregate(Sum('monto_1t_ampliacion'))
		total_monto_1t_ampliacion = total_monto_1t_ampliacion_dict['monto_1t_ampliacion__sum']
	
		total_monto_1t_reduccion_dict = programas.aggregate(Sum('monto_1t_reduccion'))
		total_monto_1t_reduccion = total_monto_1t_reduccion_dict['monto_1t_reduccion__sum']
	
		total_monto_1t_modificado_dict = programas.aggregate(Sum('monto_1t_modificado'))
		total_monto_1t_modificado = total_monto_1t_modificado_dict['monto_1t_modificado__sum']

		total_monto_1t_ejercido_dict = programas.aggregate(Sum('monto_1t_ejercido'))
		total_monto_1t_ejercido = total_monto_1t_ejercido_dict['monto_1t_ejercido__sum']

		total_monto_1t_por_ejercer_dict = programas.aggregate(Sum('monto_1t_por_ejercer'))
		total_monto_1t_por_ejercer = total_monto_1t_por_ejercer_dict['monto_1t_por_ejercer__sum']

		total_monto_2t_autorizado_dict = programas.aggregate(Sum('monto_2t_autorizado'))
		total_monto_2t_autorizado = total_monto_2t_autorizado_dict['monto_2t_autorizado__sum']

		total_monto_2t_ampliacion_dict = programas.aggregate(Sum('monto_2t_ampliacion'))
		total_monto_2t_ampliacion = total_monto_2t_ampliacion_dict['monto_2t_ampliacion__sum']
	
		total_monto_2t_reduccion_dict = programas.aggregate(Sum('monto_2t_reduccion'))
		total_monto_2t_reduccion = total_monto_2t_reduccion_dict['monto_2t_reduccion__sum']
	
		total_monto_2t_modificado_dict = programas.aggregate(Sum('monto_2t_modificado'))
		total_monto_2t_modificado = total_monto_2t_modificado_dict['monto_2t_modificado__sum']

		total_monto_2t_ejercido_dict = programas.aggregate(Sum('monto_2t_ejercido'))
		total_monto_2t_ejercido = total_monto_2t_ejercido_dict['monto_2t_ejercido__sum']

		total_monto_2t_por_ejercer_dict = programas.aggregate(Sum('monto_2t_por_ejercer'))
		total_monto_2t_por_ejercer = total_monto_2t_por_ejercer_dict['monto_2t_por_ejercer__sum']

		total_monto_3t_autorizado_dict = programas.aggregate(Sum('monto_3t_autorizado'))
		total_monto_3t_autorizado = total_monto_3t_autorizado_dict['monto_3t_autorizado__sum']

		total_monto_3t_ampliacion_dict = programas.aggregate(Sum('monto_3t_ampliacion'))
		total_monto_3t_ampliacion = total_monto_3t_ampliacion_dict['monto_3t_ampliacion__sum']
	
		total_monto_3t_reduccion_dict = programas.aggregate(Sum('monto_3t_reduccion'))
		total_monto_3t_reduccion = total_monto_3t_reduccion_dict['monto_3t_reduccion__sum']
	
		total_monto_3t_modificado_dict = programas.aggregate(Sum('monto_3t_modificado'))
		total_monto_3t_modificado = total_monto_3t_modificado_dict['monto_3t_modificado__sum']

		total_monto_3t_ejercido_dict = programas.aggregate(Sum('monto_3t_ejercido'))
		total_monto_3t_ejercido = total_monto_3t_ejercido_dict['monto_3t_ejercido__sum']

		total_monto_3t_por_ejercer_dict = programas.aggregate(Sum('monto_3t_por_ejercer'))
		total_monto_3t_por_ejercer = total_monto_3t_por_ejercer_dict['monto_3t_por_ejercer__sum']

		total_monto_4t_autorizado_dict = programas.aggregate(Sum('monto_4t_autorizado'))
		total_monto_4t_autorizado = total_monto_4t_autorizado_dict['monto_4t_autorizado__sum']

		total_monto_4t_ampliacion_dict = programas.aggregate(Sum('monto_4t_ampliacion'))
		total_monto_4t_ampliacion = total_monto_4t_ampliacion_dict['monto_4t_ampliacion__sum']
	
		total_monto_4t_reduccion_dict = programas.aggregate(Sum('monto_4t_reduccion'))
		total_monto_4t_reduccion = total_monto_4t_reduccion_dict['monto_4t_reduccion__sum']
	
		total_monto_4t_modificado_dict = programas.aggregate(Sum('monto_4t_modificado'))
		total_monto_4t_modificado = total_monto_4t_modificado_dict['monto_4t_modificado__sum']

		total_monto_4t_ejercido_dict = programas.aggregate(Sum('monto_4t_ejercido'))
		total_monto_4t_ejercido = total_monto_4t_ejercido_dict['monto_4t_ejercido__sum']

		total_monto_4t_por_ejercer_dict = programas.aggregate(Sum('monto_4t_por_ejercer'))
		total_monto_4t_por_ejercer = total_monto_4t_por_ejercer_dict['monto_4t_por_ejercer__sum']
				
		context = {
			'programas': programas,

			'total_monto_anual_autorizado': total_monto_anual_autorizado,
			'total_monto_anual_ampliacion': total_monto_anual_ampliacion,
			'total_monto_anual_reduccion': total_monto_anual_reduccion,
			'total_monto_anual_modificado': total_monto_anual_modificado,
			'total_monto_anual_ejercido': total_monto_anual_ejercido,
			'total_monto_anual_por_ejercer': total_monto_anual_por_ejercer,

			'total_monto_1t_autorizado': total_monto_1t_autorizado,
			'total_monto_1t_ampliacion': total_monto_1t_ampliacion,
			'total_monto_1t_reduccion': total_monto_1t_reduccion,
			'total_monto_1t_modificado': total_monto_1t_modificado,
			'total_monto_1t_ejercido': total_monto_1t_ejercido,
			'total_monto_1t_por_ejercer': total_monto_1t_por_ejercer,

			'total_monto_2t_autorizado': total_monto_2t_autorizado,
			'total_monto_2t_ampliacion': total_monto_2t_ampliacion,
			'total_monto_2t_reduccion': total_monto_2t_reduccion,
			'total_monto_2t_modificado': total_monto_2t_modificado,
			'total_monto_2t_ejercido': total_monto_2t_ejercido,
			'total_monto_2t_por_ejercer': total_monto_2t_por_ejercer,

			'total_monto_3t_autorizado': total_monto_3t_autorizado,
			'total_monto_3t_ampliacion': total_monto_3t_ampliacion,
			'total_monto_3t_reduccion': total_monto_3t_reduccion,
			'total_monto_3t_modificado': total_monto_3t_modificado,
			'total_monto_3t_ejercido': total_monto_3t_ejercido,
			'total_monto_3t_por_ejercer': total_monto_3t_por_ejercer,

			'total_monto_4t_autorizado': total_monto_4t_autorizado,
			'total_monto_4t_ampliacion': total_monto_4t_ampliacion,
			'total_monto_4t_reduccion': total_monto_4t_reduccion,
			'total_monto_4t_modificado': total_monto_4t_modificado,
			'total_monto_4t_ejercido': total_monto_4t_ejercido,
			'total_monto_4t_por_ejercer': total_monto_4t_por_ejercer,


		}
		return render(request, template_name, context)

#Lista de capitulos
class ListViewCapitulos(View):
	@method_decorator(login_required)
	def get(self, request, pk):
		template_name = "presupuesto/listCapitulos.html"
		programa = get_object_or_404(Programa, pk=pk)
		capitulos = Capitulo.objects.filter(programa=programa).order_by('codigo')

		total_monto_anual_autorizado_dict = Capitulo.objects.filter(programa=programa).aggregate(Sum('monto_anual_autorizado'))
		total_monto_anual_autorizado = total_monto_anual_autorizado_dict['monto_anual_autorizado__sum']

		total_monto_anual_ampliacion_dict = Capitulo.objects.filter(programa=programa).aggregate(Sum('monto_anual_ampliacion'))
		total_monto_anual_ampliacion = total_monto_anual_ampliacion_dict['monto_anual_ampliacion__sum']		

		total_monto_anual_reduccion_dict = Capitulo.objects.filter(programa=programa).aggregate(Sum('monto_anual_reduccion'))
		total_monto_anual_reduccion = total_monto_anual_reduccion_dict['monto_anual_reduccion__sum']

		total_monto_anual_modificado_dict = Capitulo.objects.filter(programa=programa).aggregate(Sum('monto_anual_modificado'))
		total_monto_anual_modificado = total_monto_anual_modificado_dict['monto_anual_modificado__sum']

		total_monto_anual_ejercido_dict = Capitulo.objects.filter(programa=programa).aggregate(Sum('monto_anual_ejercido'))
		total_monto_anual_ejercido = total_monto_anual_ejercido_dict['monto_anual_ejercido__sum']

		total_monto_anual_por_ejercer_dict = Capitulo.objects.filter(programa=programa).aggregate(Sum('monto_anual_por_ejercer'))
		total_monto_anual_por_ejercer = total_monto_anual_por_ejercer_dict['monto_anual_por_ejercer__sum']

		#Sumatoria del primer trimestre
		total_monto_1t_autorizado_dict = Capitulo.objects.filter(programa=programa).aggregate(Sum('monto_1t_autorizado'))

presupuesto/templates/presupuesto/createMes.html
{%extends 'baseUser.html'%}

{% load bootstrap %}

{%block content%}

	<form action="." method="post">
		{%csrf_token%}
		{{NuevoMesForm | bootstrap}}
		<a href="{%url 'presupuesto:ListViewMeses' partida.pk%}"><input type="submit" value="Crear"></a>
		<a href="{%url 'presupuesto:ListViewMeses' partida.pk%}"><input class="" type="button" value="Cancelar"></a>
	</form>

{%endblock content%}

presupuesto/templates/presupuesto/deleteCapitulo.html
{%extends 'baseUser.html'%}

{%block content%}

	<div class="row justify-content-center text-center">
		<div class="col-xs-12">
			<form action="." method="post">
				<p>¿Estas seguro de querer borrar el capítulo <em>{{capitulo.codigo}} {{capitulo.nombre}}</em>?</p>
				{%csrf_token%}
				<input type="submit" value="Si">
				<a href="{%url 'presupuesto:ListViewCapitulos' programa.pk%}"><input class="" type="button" value="Cancelar"></a>
			</form>
		</div>
	</div>

{%endblock content%}

presupuesto/templates/presupuesto/deleteMes.html
{%extends 'baseUser.html'%}

{%block content%}

	<div class="row justify-content-center text-center">
		<div class="col-xs-12">
			<form action="." method="post">
				<p>	¿Esta seguro de querer borrar el mes de <em>
						{%if mes.mes == 1%}
							Enero
						{%elif mes.mes == 2%}
							Febrero
						{%elif mes.mes == 3%}
							Marzo
						{%elif mes.mes == 4%}
							Abril
						{%elif mes.mes == 5%}
							Mayo
						{%elif mes.mes == 6%}
							Junio
						{%elif mes.mes == 7%}
							Julio
						{%elif mes.mes == 8%}
							Agosto
						{%elif mes.mes == 9%}
							Septiembre
						{%elif mes.mes == 10%}
							Octubre
						{%elif mes.mes == 11%}
							Noviembre
						{%elif mes.mes == 12%}
							Diciembre
						{%endif%}?</em></p>
						{%csrf_token%}

				<input type="submit" value="Si">
				<a href="{%url 'presupuesto:ListViewMeses' partida.pk%}"><input class="" type="button" value="Cancelar"></a>
			</form>
		</div>
	</div>
	
{%endblock content%}

presupuesto/templates/presupuesto/deletePartida.html
<p>¿Estas seguro de querer borrar la partida <em>{{partida.codigo}} {{partida.descripcion}}</em>?</p>
<form action="." method="post">
	{%csrf_token%}
	<input type="submit" value="Si">
	<a href="{%url 'presupuesto:ListViewPartidas' capitulo.pk%}"><input class="" type="button" value="Cancelar"></a>
</form>

presupuesto/templates/presupuesto/listMeses.html
{%extends 'baseUser.html'%}

{%block content%}

{% load humanize %}

	<h4 class="text-center">Lista de meses de la partida {{partida.codigo}} {{partida.descripcion}} del capitulo {{capitulo.codigo}} {{capitulo.nombre}} del programa {{programa.nombre}}</h4>

	<ul class="nav nav-pills">

		{%if request.user.username == "administrador"%}
		
		<li class="nav-item">
			<a class="nav-link" href="{%url 'presupuesto:CreateViewMes' partida.pk%}">Crear mes</a>
		</li>

		{%endif%}

		<li class="nav-item">
			<a class="nav-link" href="{%url 'presupuesto:ListViewPartidas' capitulo.pk%}">Regresar</a>
		</li>
	</ul>
		
	<div class="table-responsive">
		<table class="table table-striped table-bordered">
			<thead>
				<th>Mes</th>

				{%if request.user.username == "administrador"%}

				<th>Autorizado</th>
				<th>Ampliación</th>
				<th>Reducción</th>
				<th>Modificado</th>
				<th>Ejercido</th>

				{%endif%}

				<th>Por ejercer</th>
	
				{%if request.user.username == "administrador"%}
	
				<th colspan="3">Acciones</th>
	
				{%else%}
	
				<th colspan="5">Acciones</th>
	
				{%endif%}

			</thead>
			<tbody>

		{%for mes in meses%}
			
				<tr>
					<td>
						{%if mes.mes == 1%}
							Enero
						{%elif mes.mes == 2%}
							Febrero
						{%elif mes.mes == 3%}
							Marzo
						{%elif mes.mes == 4%}
							Abril
						{%elif mes.mes == 5%}
							Mayo		
						{%elif mes.mes == 6%}
							Junio
						{%elif mes.mes == 7%}
							Julio
						{%elif mes.mes == 8%}
							Agosto
						{%elif mes.mes == 9%}
							Septiembre
						{%elif mes.mes == 10%}
							Octubre
						{%elif mes.mes == 11%}
							Noviembre
						{%elif mes.mes == 12%}
							Diciembre
						{%endif%}
					</td>

					{%if request.user.username == "administrador"%}

					<td>${{mes.monto_autorizado|intcomma}}</td>
					<td>${{mes.monto_ampliacion|intcomma}}</td>
					<td>${{mes.monto_reduccion|intcomma}}</td>
					<td>${%if mes.MontoModificado is NONE%}{{mes.monto_modificado|intcomma}}{%endif%}</td>
					<td>${{mes.monto_ejercido|intcomma}}</td>

					{%endif%}
					<td>${%if mes.MontoPorEjercer is NONE%}{{mes.monto_por_ejercer|intcomma}}{%endif%}</td>

					{%if request.user.username == "administrador"%}
					
					<td><a href="{%url 'presupuesto:UpdateViewMesAmpliacion' mes.pk%}">Ampliar</a></td>
					<td><a href="{%url 'presupuesto:UpdateViewMesReduccion' mes.pk%}">Reducir</a></td>
					<td><a href="{%url 'presupuesto:UpdateViewMes' mes.pk%}">Editar</a></td>
					<td><a href="{%url 'presupuesto:DeleteViewMes' mes.pk%}">Eliminar</a></td>

					<td><a href="{%url 'presupuesto:UpdateViewMesEjercido' mes.pk%}">Ejercer</a></td>

					{%else%}

					<td><a href="{%url 'presupuesto:UpdateViewMesEjercido' mes.pk%}">Realizar SRF para un empleado</a></td>

					<td><a href="{%url 'presupuesto:UpdateViewMesEjercido2' mes.pk%}">Realizar SRF para un proveedor</a></td>

					{%endif%}

					<td><a href="{%url 'solicitudes:ListViewSolicitudesPorMes' mes.pk%}">Lista de SRF</a></td>
				</tr>

		{%empty%}
				
				<tr>
					<td colspan="12"><p align="center">Lista de meses vacia</p></td>
				</tr>
			
		{%endfor%}
		
				<tr>
					<td><p align="right">Total</p></td>

					{%if request.user.username == "administrador"%}

					<td>{%if total_monto_autorizado is None%}
						{%else%}
							${{total_monto_autorizado|intcomma}}
						{%endif%}
					</td>
					<td>{%if total_monto_ampliacion is None%}
						{%else%}
							${{total_monto_ampliacion|intcomma}}
						{%endif%}
					</td>
					<td>{%if total_monto_reduccion is None%}
						{%else%}
							${{total_monto_reduccion|intcomma}}
						{%endif%}
					</td>
					<td>{%if total_monto_modificado is None%}
						{%else%}
							${{total_monto_modificado|intcomma}}
						{%endif%}
					</td>
					<td>{%if total_monto_ejercido is None%}
						{%else%}
							${{total_monto_ejercido|intcomma}}
						{%endif%}
					</td>

					{%endif%}
					
					<td>{%if total_monto_por_ejercer is None%}
						{%else%}
							${{total_monto_por_ejercer|intcomma}}
						{%endif%}
					</td>
				</tr>
			</tbody>
		</table>
	</div>

{%endblock content%}

presupuesto/templates/presupuesto/programa_form.html
{%extends 'baseUser.html'%}

{% load bootstrap %}

{%block content%}

	{%if object%}
	<h3>Edita el programa <i>{{object}}</i></h3>
	{%else%}
	<h3>Crea un programa</h3>
	{%endif%}

	<form method="post" enctype="multipart/form-data">
		{%csrf_token%}
		{{form | bootstrap}}
		<input type="submit" value="Guardar">

		<a href="{%url 'presupuesto:ListViewProgramas'%}"><input class="" type="button" value="Cancelar"></a>
	</form>

{%endblock content%}

presupuesto/templates/presupuesto/updateMes.html
{%extends 'baseUser.html'%}

{% load bootstrap %}

{%block content%}

	<h4>Edita el mes de <em>
			{%if mes.mes == 1%}
				Enero
			{%elif mes.mes == 2%}
				Febrero
			{%elif mes.mes == 3%}
				Marzo
			{%elif mes.mes == 4%}
				Abril
			{%elif mes.mes == 5%}
				Mayo
			{%elif mes.mes == 6%}
				Junio
			{%elif mes.mes == 7%}
				Julio
			{%elif mes.mes == 8%}
				Agosto
			{%elif mes.mes == 9%}
				Septiembre
			{%elif mes.mes == 10%}
				Octubre
			{%elif mes.mes == 11%}
				Noviembre
			{%elif mes.mes == 12%}
				Diciembre
			{%endif%}</em> de la partida {{partida.codigo}} {{partida.descripcion}}</h4>
	<form action="." method="post">
		{%csrf_token%}
		{{EdicionMesForm | bootstrap}}
			<input type="submit" value="Guardar cambios">
			<a href="{%url 'presupuesto:ListViewMeses' partida.pk%}"><input class="" type="button" value="Cancelar"></a>
	</form>

{%endblock content%}