CITNOVA/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import urls as accountsUrls
from solicitudes import urls as solicitudesUrls
from presupuesto import urls as presupuestoUrls
#Libreria para importar imagenes
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include(accountsUrls, namespace="accounts")),
	url(r'^', include(solicitudesUrls, namespace="solicitudes")),
    url(r'^', include(presupuestoUrls, namespace="presupuesto")),
    #Direccion para buscar imagenes
    url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs ={'document_root':settings.MEDIA_ROOT}
    ),
]

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout

urlpatterns = [
	#urls de empleados
	url(r'^accounts/director/actualizar/(?P<pk>\d+)/$', views.UpdateViewDirector.as_view(), name="UpdateViewDirector"),
	url(r'^accounts/director/nuevo/$',views.CreateViewDirector.as_view(), name='CreateViewDirector'),
	url(r'^accounts/directores/$',views.ListViewDirectores.as_view(), name='ListViewDirectores'),

	#urls de empleados
	url(r'^accounts/empleado/desactivar/(?P<pk>\d+)/$', views.DesactivateViewUser.as_view(), name="DesactivateViewUser"),
	url(r'^accounts/empleado/actualizar/(?P<pk>\d+)/$', views.UpdateViewEmpleado.as_view(), name="UpdateViewEmpleado"),
	url(r'^accounts/empleado/nuevo/$',views.CreateViewEmpleado.as_view(), name='CreateViewEmpleado'),
	url(r'^accounts/empleados/$',views.ListViewEmpleados.as_view(), name='ListViewEmpleados'),

	#urls de proveedores
	url(r'^accounts/proveedor/actualizar/(?P<pk>\d+)/$', views.UpdateViewProveedor.as_view(), name="UpdateViewProveedor"),
	url(r'^accounts/proveedor/nuevo/$',views.CreateViewProveedor.as_view(), name='CreateViewProveedor'),
	url(r'^accounts/proveedores/$',views.ListViewProveedores.as_view(), name='ListViewProveedores'),

	#urls de bancos
	url(r'^accounts/bancos/actualizar/(?P<pk>\d+)$',views.UpdateViewBanco.as_view(), name='UpdateViewBanco'),
	url(r'^accounts/bancos/eliminar/(?P<pk>\d+)$',views.DeleteViewBanco.as_view(), name='DeleteViewBanco'),
	url(r'^accounts/bancos/nuevo/$',views.CreateViewBanco.as_view(), name='CreateViewBanco'),	
	url(r'^accounts/bancos/$',views.ListViewBancos.as_view(), name='ListViewBancos'),
	
	#urls de departamentos
	url(r'^accounts/departamentos/actualizar/(?P<pk>\d+)$',views.UpdateViewDepartamento.as_view(), name='UpdateViewDepartamento'),
	url(r'^accounts/departamentos/eliminar/(?P<pk>\d+)$',views.DeleteViewDepartamento.as_view(), name='DeleteViewDepartamento'),
	url(r'^accounts/departamentos/nuevo/$',views.CreateViewDepartamento.as_view(), name='CreateViewDepartamento'),	
	url(r'^accounts/departamentos/$',views.ListViewDepartamentos.as_view(), name='ListViewDepartamentos'),

	#url de perfil
	url(r'^accounts/profile/$',views.profile.as_view(), name='profile'),
	
	#url de login y logout
	url(r'^solicitudes/login/$', login,name="login"),
	url(r'^logout/$', logout, name="logout"),
]

presupuesto/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	
	url(r'^programas/capitulos/partidas/meses/actualizar/ampliacion/(?P<pk>\d+)/$', views.UpdateViewMesAmpliacion.as_view(), name="UpdateViewMesAmpliacion"),
	url(r'^programas/capitulos/partidas/meses/actualizar/reduccion/(?P<pk>\d+)/$', views.UpdateViewMesReduccion.as_view(), name="UpdateViewMesReduccion"),
	url(r'^programas/capitulos/partidas/meses/actualizar/ejercido/empleado/(?P<pk>\d+)/$', views.UpdateViewMesEjercido.as_view(), name="UpdateViewMesEjercido"),
	url(r'^programas/capitulos/partidas/meses/actualizar/ejercido/proveedor/(?P<pk>\d+)/$', views.UpdateViewMesEjercido2.as_view(), name="UpdateViewMesEjercido2"),

	url(r'^programas/capitulos/partidas/meses/nuevo/(?P<pk>\d+)/$', views.CreateViewMes.as_view(), name="CreateViewMes"),
	url(r'^programas/capitulos/partidas/meses/actualizar/(?P<pk>\d+)/$', views.UpdateViewMes.as_view(), name="UpdateViewMes"),
	url(r'^programas/capitulos/partidas/meses/eliminar/(?P<pk>\d+)/$', views.DeleteViewMes.as_view(), name="DeleteViewMes"),
	url(r'^programas/capitulos/partidas/meses/(?P<pk>\d+)/$', views.ListViewMeses.as_view(), name="ListViewMeses"),

	url(r'^programas/capitulos/partidas/nuevo/(?P<pk>\d+)/$', views.CreateViewPartida.as_view(), name="CreateViewPartida"),
	url(r'^programas/capitulos/partidas/actualizar/(?P<pk>\d+)/$', views.UpdateViewPartida.as_view(), name="UpdateViewPartida"),
	url(r'^programas/capitulos/partidas/eliminar/(?P<pk>\d+)/$', views.DeleteViewPartida.as_view(), name="DeleteViewPartida"),
	url(r'^programas/capitulos/partidas/(?P<pk>\d+)/$', views.ListViewPartidas.as_view(), name="ListViewPartidas"),

	url(r'^programas/capitulos/nuevo/(?P<pk>\d+)/$', views.CreateViewCapitulo.as_view(), name="CreateViewCapitulo"),
	url(r'^programas/capitulos/actualizar/(?P<pk>\d+)/$', views.UpdateViewCapitulo.as_view(), name="UpdateViewCapitulo"),
	url(r'^programas/capitulos/eliminar/(?P<pk>\d+)/$', views.DeleteViewCapitulo.as_view(), name="DeleteViewCapitulo"),
	url(r'^programas/capitulos/(?P<pk>\d+)/$', views.ListViewCapitulos.as_view(), name="ListViewCapitulos"),
	
	url(r'^programas/nuevo/$', views.CreateViewPrograma.as_view(), name="CreateViewPrograma"),
	url(r'^programas/actualizar/(?P<pk>\d+)/$', views.UpdateViewPrograma.as_view(), name="UpdateViewPrograma"),
	url(r'^programas/eliminar/(?P<pk>\d+)/$', views.DeleteViewPrograma.as_view(), name="DeleteViewPrograma"),
	url(r'^programas/$',views.ListViewProgramas.as_view(),name='ListViewProgramas'),
]

solicitudes/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

	url(r'^solicitudes/search/$',views.SearchSolicitudes.as_view(), name='SearchSolicitudes'),

	#Urls de detalla de solicitudes 
	url(r'^solicitudes/consultar/propias/(?P<pk>\d+)/$', views.DetailViewSolicitudPropia.as_view(), name="DetailViewSolicitudPropia"),
	url(r'^solicitudes/consultar/ajenas/(?P<pk>\d+)/$', views.DetailViewSolicitudPendiente.as_view(), name="DetailViewSolicitudPendiente"),
	url(r'^solicitudes/por_mes/(?P<pk>\d+)/$', views.ListViewSolicitudesPorMes.as_view(), name="ListViewSolicitudesPorMes"),

	#Urls de creación de solicitudes
	url(r'^solicitudes/empleado/nuevo/$',views.CreateViewSolicitudEmpleado.as_view(), name='CreateViewSolicitudEmpleado'),
	url(r'^solicitudes/proveedor/nuevo/$',views.CreateViewSolicitudProveedor.as_view(), name='CreateViewSolicitudProveedor'),	
	
	#Urls de listas de solicitudes
	url(r'^solicitudes/por_pagar/$',views.ListViewSolicitudesPendientes.as_view(), name='ListViewSolicitudesPendientes'),
	url(r'^solicitudes/pagadas/$',views.ListViewSolicitudesPagadas.as_view(), name='ListViewSolicitudesPagadas'),
	url(r'^solicitudes/$',views.ListViewSolicitudesPropias.as_view(), name='ListViewSolicitudesPropias'),

]

templates/baseUser.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
    	<title>Administración CITNOVA</title>
    
        <meta name="viewport" content="width=device-width, user-scalable=no">
        <link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap.min.css'%}">
        <link rel="stylesheet" type="text/css" href="{%static 'css/font-awesome.min.css'%}">
        <link rel="stylesheet" type="text/css" href="{%static 'css/estilos.css'%}">

    </head>
    <body>
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded navbar-default">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="#"><img src="{%static 'img/logo.png'%}" height="32"> Presupuestos y SRF</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                </ul>
                <ul class="navbar-nav">

                    {%if request.user.is_authenticated%}

                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'accounts:profile'%}">Inicio</a>
                    </li>

                    {%if request.user.perfil.puesto == "Director"%}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Empleados</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'accounts:CreateViewEmpleado' %}">Registrar</a>
                            <a class="dropdown-item" href="{% url 'accounts:ListViewEmpleados' %}">Catalogo</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Proveedores</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'accounts:CreateViewProveedor' %}">Registrar</a>
                            <a class="dropdown-item" href="{% url 'accounts:ListViewProveedores' %}">Catalogo</a>
                        </div>
                    </li>              
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Solicitudes de Recurso Financiero</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'solicitudes:ListViewSolicitudesPropias' %}">Mis solicitudes</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Programas</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'presupuesto:ListViewProgramas' %}">Catalogo</a>
                        </div>
                    </li> 
                    
                    {%endif%}
                    {%if request.user.username == "administrador"%}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Programas</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{%url 'presupuesto:CreateViewPrograma' %}">Crear</a>
                            <a class="dropdown-item" href="{% url 'presupuesto:ListViewProgramas' %}">Catalogo</a>
                        </div>
                    </li>  


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Directores</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{%url 'accounts:CreateViewDirector' %}">Crear</a>
                            <a class="dropdown-item" href="{% url 'accounts:ListViewDirectores' %}">Catalogo</a>
                        </div>
                    </li>  
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Direcciones</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{%url 'accounts:CreateViewDepartamento' %}">Crear</a>
                            <a class="dropdown-item" href="{% url 'accounts:ListViewDepartamentos' %}">Catalogo</a>
                        </div>
                    </li>  

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Solicitudes de Recurso Financiero</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'solicitudes:ListViewSolicitudesPendientes' %}">Pendientes</a>
                            <a class="dropdown-item" href="{% url 'solicitudes:ListViewSolicitudesPagadas' %}">Pagadas</a>
                            <a class="dropdown-item" href="{% url 'solicitudes:SearchSolicitudes' %}">Buscar</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Bancos</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{%url 'accounts:CreateViewBanco' %}">Crear</a>
                            <a class="dropdown-item" href="{% url 'accounts:ListViewBancos' %}">Catalogo</a>
                        </div>
                    </li> 

                    {%endif%}

                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'accounts:logout'%}">Salir</a>
                    </li>

                    {%endif%}

                </ul>
            </div>
        </nav>

        <div class="container">
            <br>
            {%block content%}
            {%endblock content%}
        </div>

        <script type="text/javascript" src="{%static 'js/jquery.js'%}"></script>
        <script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>
    </body>
</html>