CITNOVA/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import urls as accountsUrls
from solicitudes import urls as solicitudesUrls
from presupuesto import urls as presupuestoUrls
#Libreria para importar imagenes
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include(accountsUrls, namespace="accounts")),
	url(r'^', include(solicitudesUrls, namespace="solicitudes")),
    url(r'^', include(presupuestoUrls, namespace="presupuesto")),
    #Direccion para buscar imagenes
    url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs ={'document_root':settings.MEDIA_ROOT}
    ),
]

solicitudes/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

	url(r'^solicitudes/search/$',views.SearchSolicitudes.as_view(), name='SearchSolicitudes'),

	#Urls de detalla de solicitudes 
	url(r'^solicitudes/consultar/propias/(?P<pk>\d+)/$', views.DetailViewSolicitudPropia.as_view(), name="DetailViewSolicitudPropia"),
	url(r'^solicitudes/consultar/ajenas/(?P<pk>\d+)/$', views.DetailViewSolicitudPendiente.as_view(), name="DetailViewSolicitudPendiente"),
	url(r'^solicitudes/por_mes/(?P<pk>\d+)/$', views.ListViewSolicitudesPorMes.as_view(), name="ListViewSolicitudesPorMes"),

	#Urls de creación de solicitudes
	url(r'^solicitudes/empleado/nuevo/$',views.CreateViewSolicitudEmpleado.as_view(), name='CreateViewSolicitudEmpleado'),
	url(r'^solicitudes/proveedor/nuevo/$',views.CreateViewSolicitudProveedor.as_view(), name='CreateViewSolicitudProveedor'),	
	
	#Urls de listas de solicitudes
	url(r'^solicitudes/por_pagar/$',views.ListViewSolicitudesPendientes.as_view(), name='ListViewSolicitudesPendientes'),
	url(r'^solicitudes/pagadas/$',views.ListViewSolicitudesPagadas.as_view(), name='ListViewSolicitudesPagadas'),
	url(r'^solicitudes/$',views.ListViewSolicitudesPropias.as_view(), name='ListViewSolicitudesPropias'),

]

solicitudes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from decimal import Decimal
from presupuesto.models import Mes

class SolicitudRecursoFinanciero(models.Model):
	MetodoPago_CHOICES = {
		("CHEQUE", "CHEQUE"),
		("TRANSFERENCIA ELECTRÓNICA", "TRANSFERENCIA ELECTRÓNICA")
	}
	folio = models.CharField(max_length=10)
	mes = models.ForeignKey(Mes, null=True, blank=True)
	a_nombre_de = models.ForeignKey(User, related_name="a_nombre_de")
	concepto = models.TextField()
	importe_numero = models.DecimalField(max_digits=20,decimal_places=2)
	importe_letra = models.CharField(max_length=100)
	metodo_pago = models.CharField(max_length=30, choices= MetodoPago_CHOICES)
	clabe = models.CharField(max_length=100)
	creacion = models.DateTimeField(default=timezone.now)
	solicitante = models.ForeignKey(User, related_name="solicitante")
	pagado = models.BooleanField(default=False)
	comprobante = models.FileField(upload_to='Comprobantes/%Y/%m/%d/', null=True, blank=True)
	fecha_pagado = models.DateTimeField(blank=True, null=True)
	cuenta_bancaria_del_programa = models.CharField(max_length=30,  null=True, blank=True)
	class Meta:
		ordering = ['creacion']

	def __str__(self):
		return '{}'.format(self.folio)

	def FechaPagado(self):
		if self.pagado==True:
			self.fecha_pagado = timezone.now()
			self.save()

solicitudes/forms.py
from .models import *
from accounts.models import Departamento
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import Select
from django.contrib import admin
import datetime
from django.db.models import Q

class SolicitudRecursoFinancieroCreateForm(forms.ModelForm):

	class Meta:
		model = SolicitudRecursoFinanciero
		fields = ('a_nombre_de' ,'concepto', 'importe_numero', 'importe_letra', 'metodo_pago', 'comprobante',)

	def __init__(self, departamento=None, **kwargs):
		super(SolicitudRecursoFinancieroCreateForm, self).__init__(**kwargs)
		if departamento:
			hoy = datetime.datetime.now()
			self.fields['a_nombre_de'].queryset = User.objects.filter(is_active=True, departamento=departamento).order_by('first_name', 'last_name')
#			self.fields['programa'].queryset = Programa.objects.filter(departamento=departamento, año=hoy.year)

	def clean(self):
		cd = self.cleaned_data
		return cd
		
class SolicitudRecursoFinancieroCreateForm2(forms.ModelForm):

	class Meta:
		model = SolicitudRecursoFinanciero
		fields = ('a_nombre_de', 'concepto', 'importe_numero', 'importe_letra', 'metodo_pago', 'comprobante')

	def __init__(self, *args, **kwargs):
		super(SolicitudRecursoFinancieroCreateForm2, self).__init__(**kwargs)
		self.fields['a_nombre_de'].queryset = User.objects.filter(is_active=True, departamento__isnull=True, is_staff=False).order_by('first_name', 'last_name')

	def clean(self):
		cd = self.cleaned_data
		return cd
		
class SolicitudRecursoFinancieroEditForm(forms.ModelForm):

	class Meta:
		model = SolicitudRecursoFinanciero
		fields = ('pagado',)

solicitudes/views.py
from django.shortcuts import render, redirect
from django.views.generic import View 
from .models import *
from .forms import *
from accounts.models import Perfil
import datetime
from presupuesto.models import *
from django.contrib import messages
from datetime import timedelta
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models import Count

hoy = datetime.datetime.now()
#Lista de solicitudes propias
class ListViewSolicitudesPorMes(View):
	@method_decorator(login_required)
	def get(self, request, pk):
		template_name = "solicitudes/listSolitudesPorMes.html"
		mes = get_object_or_404(Mes, pk=pk)
		solicitudes = SolicitudRecursoFinanciero.objects.filter(mes=mes)

		context = {
			'solicitudes': solicitudes,
		}
		return render(request,template_name,context)

#Lista de solicitudes creadas por un usuario logeado
class ListViewSolicitudesPropias(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "solicitudes/listSolitudesPropias.html"
		solicitudes = SolicitudRecursoFinanciero.objects.filter(creacion__year=hoy.year, creacion__month=hoy.month, solicitante=request.user)

		context = {
			'solicitudes': solicitudes,
		}
		return render(request,template_name,context)

#Creación de Solicitud para un empleado
class CreateViewSolicitudEmpleado(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "solicitudes/createSolicitudEmpleado.html"
		user = User.objects.get(pk=request.user.pk)
		departamento = Departamento.objects.get(user=user)
		folio = str(departamento.codigo) + "-" + str(SolicitudRecursoFinanciero.objects.filter(folio__contains=departamento.codigo, creacion__year=hoy.year).count() + 1) + "-" + str(hoy.year)

		programas = Programa.objects.filter(año=hoy.year, departamento=departamento)
		SolicitudRecursoFinancieroForm = SolicitudRecursoFinancieroCreateForm(departamento=departamento, )
		context = {
			'departamento': departamento,
			'folio': folio,
			'SolicitudRecursoFinancieroForm': SolicitudRecursoFinancieroForm,
			'programas': programas,
		}
		return render(request,template_name,context)
	def post(self,request):
		template_name = "solicitudes/createSolicitudEmpleado.html"
		user = User.objects.get(pk=request.user.pk)
		departamento = Departamento.objects.get(user=user)
		folio = str(departamento.codigo) + "-" + str(SolicitudRecursoFinanciero.objects.filter(folio__contains=departamento.codigo, creacion__year=hoy.year).count() + 1) + "-" + str(hoy.year)
		NuevoSolicitudRecursoFinancieroForm = SolicitudRecursoFinancieroCreateForm(data=request.POST, files=request.FILES)
		
		empleado = User.objects.get(pk=request.POST.get("a_nombre_de"))
		perfilEmpleado = Perfil.objects.get(user=empleado)

		if NuevoSolicitudRecursoFinancieroForm.is_valid(): 
			NuevoSolicitudRecursoFinanciero = NuevoSolicitudRecursoFinancieroForm.save(commit=False)
			NuevoSolicitudRecursoFinanciero.folio = folio
			NuevoSolicitudRecursoFinanciero.clabe =  perfilEmpleado.CLABE
			NuevoSolicitudRecursoFinanciero.solicitante = user
			NuevoSolicitudRecursoFinanciero.save()

		return redirect("solicitudes:ListViewSolicitudesPropias")

#Creación de Solicitud para un proveedor
class CreateViewSolicitudProveedor(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "solicitudes/createSolicitudProveedor.html"
		user = User.objects.get(pk=request.user.pk)
		departamento = Departamento.objects.get(user=user)
		folio = str(departamento.codigo) + "-" + str(SolicitudRecursoFinanciero.objects.filter(folio__contains=departamento.codigo, creacion__year=hoy.year).count() + 1) + "-" + str(hoy.year)
		SolicitudRecursoFinancieroForm = SolicitudRecursoFinancieroCreateForm2()

		context = {
			'departamento': departamento,
			'folio': folio,
			'SolicitudRecursoFinancieroForm': SolicitudRecursoFinancieroForm,
		}
		return render(request,template_name,context)
	def post(self,request):
		template_name = "solicitudes/createSolicitudProveedor.html"
		user = User.objects.get(pk=request.user.pk)
		departamento = Departamento.objects.get(user=user)
		folio = str(departamento.codigo) + "-" + str(SolicitudRecursoFinanciero.objects.filter(folio__contains=departamento.codigo, creacion__year=hoy.year).count() + 1) + "-" + str(hoy.year)
		NuevoSolicitudRecursoFinancieroForm = SolicitudRecursoFinancieroCreateForm2(data=request.POST, files=request.FILES)
		
		proveedor = User.objects.get(pk=request.POST.get("a_nombre_de"))
		perfilProveedor = Perfil.objects.get(user=proveedor)

		if NuevoSolicitudRecursoFinancieroForm.is_valid(): 
			NuevoSolicitudRecursoFinanciero = NuevoSolicitudRecursoFinancieroForm.save(commit=False)
			NuevoSolicitudRecursoFinanciero.folio = folio
			NuevoSolicitudRecursoFinanciero.clabe =  perfilProveedor.CLABE
			NuevoSolicitudRecursoFinanciero.solicitante = user
			NuevoSolicitudRecursoFinanciero.save()

		return redirect("solicitudes:ListViewSolicitudesPropias")

#Detalle de una Solicitud propia
class DetailViewSolicitudPropia(View):
	def get(self, request, pk):
		template_name = "solicitudes/detailSolicitudPropia.html"
		solicitud = get_object_or_404(SolicitudRecursoFinanciero, pk=pk)
		mes = Mes.objects.get(pk=solicitud.mes.pk)
		partida = Partida.objects.get(mes=mes)
		capitulo = Capitulo.objects.get(partida=partida)
		programa = Programa.objects.get(capitulo=capitulo)
		context = {
			'solicitud': solicitud,
			'mes': mes,
			'partida': partida,
			'capitulo': capitulo,
			'programa': programa,
		}
		return render(request, template_name, context)

#Lista de Solicitudes por pagar
class ListViewSolicitudesPendientes(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "solicitudes/listSolitudesPendientes.html"
		solicitudes = SolicitudRecursoFinanciero.objects.filter(pagado=False)		
		context = {
			'solicitudes': solicitudes,
		}
		return render(request,template_name,context)

#Detalle de una Solicitud por pagar
class DetailViewSolicitudPendiente(View):
	@method_decorator(login_required)
	def get(self, request, pk):
		template_name = "solicitudes/detailSolicitudPendiente.html"
		solicitud = get_object_or_404(SolicitudRecursoFinanciero, pk=pk)
		EdicionSolicitudForm=SolicitudRecursoFinancieroEditForm(instance=solicitud)
		mes = Mes.objects.get(pk=solicitud.mes.pk)
		partida = Partida.objects.get(mes=mes)
		capitulo = Capitulo.objects.get(partida=partida)
		programa = Programa.objects.get(capitulo=capitulo)
		context = {
			'solicitud': solicitud,
			'EdicionSolicitudForm': EdicionSolicitudForm,
			'mes': mes,
			'partida': partida,
			'capitulo': capitulo,
			'programa': programa,
		}
		return render(request, template_name, context)
	def post (self, request, pk):
		template_name = "solicitudes/detailSolicitudPendiente.html"
		solicitud = get_object_or_404(SolicitudRecursoFinanciero, pk=pk)
		EdicionSolicitudForm=SolicitudRecursoFinancieroEditForm(instance=solicitud, data=request.POST)

		if EdicionSolicitudForm.is_valid():
			EdicionSolicitudForm.save()
			messages.success(request, "Se cambió el estatus correctamente")			

		return redirect("solicitudes:DetailViewSolicitudPendiente", pk=solicitud.pk)

#Lista de solicitudes pagadas en la ultima semana
class ListViewSolicitudesPagadas(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "solicitudes/listSolitudesPagadas.html"
		semana_pasada = hoy - timedelta(days=7)
		solicitudes = SolicitudRecursoFinanciero.objects.filter(fecha_pagado__isnull=False, fecha_pagado__range=[semana_pasada, hoy])
		context = {
			'solicitudes': solicitudes,
		}
		return render(request,template_name,context)

class SearchSolicitudes(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "solicitudes/searchSolitudes.html"
		query = request.GET.get("query")

		if query:
			solicitudes = SolicitudRecursoFinanciero.objects.filter(
				(
					Q(folio__contains=query) | 
					Q(concepto__contains=query) |
					Q(importe_numero__contains=query)
				), 
				creacion__year=hoy.year
			).order_by("-creacion")

			if not solicitudes.exists():
				
				users = User.objects.filter(
					(
						Q(first_name__contains=query) | 
						Q(last_name__contains=query)
					)
				)
				
				solicitudes = SolicitudRecursoFinanciero.objects.filter(
						a_nombre_de=users, 
						creacion__year=hoy.year
					).order_by("-creacion")
	
		else:
			solicitudes = []
	
		context = {
			'solicitudes': solicitudes,
		}
		return render(request,template_name, context)

solicitudes/templates/solicitudes/createSolicitudEmpleado.html
{%extends 'baseUser.html'%}

{% load bootstrap %}

{%block content%}

	<h4>Crear Solicitud de Recurso Financiero para Empleado</h4>
	<p>Folio: {{folio}}</p>
	<form action="." method="post" enctype="multipart/form-data">
		{%csrf_token%}
		{{SolicitudRecursoFinancieroForm | bootstrap}}
		<input type="submit" value="Crear solicitud">
	</form>

{%endblock content%}

solicitudes/templates/solicitudes/createSolicitudProveedor.html
{%extends 'baseUser.html'%}

{% load bootstrap %}

{%block content%}
	
	<h4>Crear Solicitud de Recurso Financiero para Proveedor</h4>
	<p>Folio: {{folio}}</p>
	<form action="." method="post" enctype="multipart/form-data">
		{%csrf_token%}
		{{SolicitudRecursoFinancieroForm | bootstrap}}	
		<input type="submit" value="Crear solicitud">
	</form>

{%endblock content%}

solicitudes/templates/solicitudes/detailSolicitudPendiente.html
{%extends 'baseUser.html'%}

{%block content%}

	<div>

	{% if messages %}

		<div class="messages">

			{% for message in messages %}
		
			<div {% if message.tags %} class="alert alert-success"{% endif %}>{{ message }}</div>
			
			{% endfor %}
		
		</div>

	{% endif %}

	</div>

	<h4>Información de solicitud</h4>
	<p>Folio: {{solicitud.folio}}</p>
	<p>Programa: {{programa.nombre}}</p>
	<p>Capitulo: {{capitulo.codigo}} {{capitulo.nombre}}</p>
	<p>Partida: {{partida.codigo}} {{partida.descripcion}}</p>
	<p>Mes: {%if mes.mes == 1%}
			Enero
		{%elif mes.mes == 2%}
			Febrero
		{%elif mes.mes == 3%}
			Marzo
		{%elif mes.mes == 4%}
			Abril
		{%elif mes.mes == 5%}
			Mayo
		{%elif mes.mes == 6%}
			Junio
		{%elif mes.mes == 7%}
			Julio
		{%elif mes.mes == 8%}
			Agosto
		{%elif mes.mes == 9%}
			Septiembre
		{%elif mes.mes == 10%}
			Octubre
		{%elif mes.mes == 11%}
			Noviembre
		{%elif mes.mes == 12%}
			Diciembre
		{%endif%}</p>
	<p>Cuenta bancaria del programa: {{solicitud.cuenta_bancaria_del_programa}}</p>
	<p>A nombre de: {{solicitud.a_nombre_de}}</p>
	<p>Concepto: {{solicitud.concepto}}</p>
	<p>Importe con numero: {{solicitud.importe_numero}}</p>
	<p>Importe con letra: {{solicitud.importe_letra}}</p>
	<p>Metodo: {{solicitud.metodo_pago}}</p>
	<p>CLABE: {{solicitud.clabe}}</p>
	<p>Creación: {{solicitud.creacion}}</p>
	<p>Status: {%if solicitud.pagado%}Pagado<p>
	<p>Fecha de pago: {{solicitud.fecha_pagado}}</p>
	<p>{%else%}Aun no sea pagado{%endif%}</p>

	{%if solicitud.comprobante%} 
	<p><a href="{{solicitud.comprobante.url}}">Ver comprobante(s)</a></p>
	{%else%}
	<p>Falta comprobante</p>
	{%endif%}
	
	{%if request.user.username == "administrador"%}

	<p><strong>Una vez concluido el proceso correspondiente, se tiene que activar la opción de pagado</strong></p>

	
	<form action="." method="post">
		{%csrf_token%}
		{{EdicionSolicitudForm.as_p}}		
		<input type="submit" value="Cambiar status">
	</form>
	{%endif%}
{%endblock content%}

solicitudes/templates/solicitudes/detailSolicitudPropia.html
{%extends 'baseUser.html'%}

{%block content%}

	<h4>Información de solicitud</h4>
	<p>Folio: {{solicitud.folio}}</p>
	<p>Programa: {{programa.nombre}}</p>
	<p>Capitulo: {{capitulo.codigo}} {{capitulo.nombre}}</p>
	<p>Partida: {{partida.codigo}} {{partida.descripcion}}</p>
	<p>Mes: {%if mes.mes == 1%}
			Enero
		{%elif mes.mes == 2%}
			Febrero
		{%elif mes.mes == 3%}
			Marzo
		{%elif mes.mes == 4%}
			Abril
		{%elif mes.mes == 5%}
			Mayo
		{%elif mes.mes == 6%}
			Junio
		{%elif mes.mes == 7%}
			Julio
		{%elif mes.mes == 8%}
			Agosto
		{%elif mes.mes == 9%}
			Septiembre
		{%elif mes.mes == 10%}
			Octubre
		{%elif mes.mes == 11%}
			Noviembre
		{%elif mes.mes == 12%}
			Diciembre
		{%endif%}</p>
	<p>Cuenta bancaria del programa: {{solicitud.cuenta_bancaria_del_programa}}</p>
	<p>A nombre de: {{solicitud.a_nombre_de}}</p>
	<p>Concepto: {{solicitud.concepto}}</p>
	<p>Importe con numero: ${{solicitud.importe_numero}}</p>
	<p>Importe con letra: {{solicitud.importe_letra}}</p>
	<p>Metodo: {{solicitud.metodo_pago}}</p>
	<p>CLABE: {{solicitud.clabe}}</p>
	<p>Creación: {{solicitud.creacion}}</p>
	<p>Status: {%if solicitud.pagado is True%}Pagada</p>
	<p>Fecha de pago: {{solicitud.fecha_pagado}}</p>
	<p>{%else%}Aún no se ha pagado{%endif%}</p>
	
	{%if solicitud.comprobante%} 
	
	<a href="{{solicitud.comprobante.url}}">Ver comprobante(s)</a>
	
	{%else%}
	
	<p>No hay comprobante</p>
	
	{%endif%}

{%endblock content%}

solicitudes/templates/solicitudes/listSolitudesPagadas.html
{%extends 'baseUser.html'%}

{%block content%}
	<h4 class="text-center">Lista de solicitudes pagadas en la ultima semana</h4>

	<div class="table-responsive">
		<table class="table">
			<thead>
				<th>Folio</th>
				<th>A nombre de</th>
				<th>Cantidad</th>
				<th>Creación</th>
				<th>Acciones</th>
			</thead>
			<tbody>

	{%for solicitud in solicitudes%}

				<tr>
					<td>{{solicitud.folio}}</td>
					<td>{{solicitud.a_nombre_de}}</td>
					<td>${{solicitud.importe_numero}}</td>
					<td>{{solicitud.creacion}}</td>
					<td><a href="{%url 'solicitudes:DetailViewSolicitudPendiente' solicitud.pk%}">Verificar</a></td>
				</tr>
	
	{%empty%}
	
				<tr>
					<td colspan="5">Lista de solicitudes vacia</td>
				</tr>	
	{%endfor%}

			</tbody>
		</table>
	</div>


{%endblock content%}

solicitudes/templates/solicitudes/listSolitudesPendientes.html
{%extends 'baseUser.html'%}

{%block content%}
	<h4 class="text-center">Lista de solicitudes por pagar</h4>

	<div class="table-responsive">
		<table class="table">
			<thead>
				<th>Folio</th>
				<th>A nombre de</th>
				<th>Cantidad</th>
				<th>Creación</th>
				<th>Acciones</th>
			</thead>
			<tbody>

	{%for solicitud in solicitudes%}

				<tr>
					<td>{{solicitud.folio}}</td>
					<td>{{solicitud.a_nombre_de}}</td>
					<td>${{solicitud.importe_numero}}</td>
					<td>{{solicitud.creacion}}</td>
					<td><a href="{%url 'solicitudes:DetailViewSolicitudPendiente' solicitud.pk%}">Confirmar pago</a></td>
				</tr>
	
	{%empty%}
	
				<tr>
					<td colspan="5">Lista de solicitudes vacia</td>
				</tr>	
	{%endfor%}

			</tbody>
		</table>
	</div>


{%endblock content%}

solicitudes/templates/solicitudes/listSolitudesPorMes.html
{%extends 'baseUser.html'%}

{%block content%}
	<h4 class="text-center">Lista de solicitudes {{mes.mes}}</h4>

	<div class="table-responsive">
		<table class="table">
			<thead>
				<th>Folio</th>
				<th>A nombre de</th>
				<th>Status</th>
				<th>Cantidad</th>
				<th>Status</th>
				<th>Acciones</th>
			</thead>
			<tbody>

	{%for solicitud in solicitudes%}

				<tr>
					<td>{{solicitud.folio}}</td>
					<td>{{solicitud.a_nombre_de}}</td>
					<td>${{solicitud.importe_numero}}</td>
					<td>{{solicitud.creacion}}</td>
					<td>{%if solicitud.pagado%}Pagado{%else%}Aun no sea pagado{%endif%}</td>
					<td><a href="{%url 'solicitudes:DetailViewSolicitudPendiente' solicitud.pk%}">Ver detalle</a></td>
				</tr>
	
	{%empty%}
	
				<tr>
					<td colspan="6">Lista de solicitudes vacia</td>
				</tr>	
	{%endfor%}

			</tbody>
		</table>
	</div>


{%endblock content%}

solicitudes/templates/solicitudes/listSolitudesPropias.html
{%extends 'baseUser.html'%}

{%block content%}
	
	<h4 class="text-center">Lista de mis solicitudes de {% now " F Y" %}</h4>

	<div class="table-responsive">
		<table class="table">
			<thead>
				<th>Folio</th>
				<th>A nombre de</th>
				<th>Cantidad</th>
				<th>Creación</th>
				<th>Status</th>
				<th>Acciones</th>
			</thead>
			<tbody>
	
	{%for solicitud in solicitudes%}
	
				<tr>
					<td>{{solicitud.folio}}</td>
					<td>{{solicitud.a_nombre_de}}</td>
					<td>${{solicitud.importe_numero}}</td>
					<td>{{solicitud.creacion}}</td>
					<td>{%if solicitud.pagado%}Pagado{%else%}Aun no sea pagado{%endif%}</td>
					<td><a href="{%url 'solicitudes:DetailViewSolicitudPropia' solicitud.pk%}">Ver información</a></td>
				</tr>

			{%empty%}

				<tr>
					<td colspan="3">Lista de solicitudes vacia</td>
				</tr>

			{%endfor%}

			</tbody>
		</table>
	</div>

{%endblock content%}

solicitudes/templates/solicitudes/searchSolitudes.html
{%extends 'baseUser.html'%}

{%block content%}

	<h4 class="text-center">Buscar solicitudes</h4>

	<form method="GET" action="">
		<input type="text" name="query" placeholder="Buscar" value="{{request.GET.query}}">
		<input type="submit" value="Buscar">
	</form>
	<br>
	<div class="table-responsive">
		<table class="table">
			<thead>
				<th>Folio</th>
				<th>A nombre de</th>
				<th>Cantidad</th>
				<th>Creación</th>
				<th>Status</th>
				<th>Acciones</th>
			</thead>
			<tbody>
	
	{%for solicitud in solicitudes%}
	
				<tr>
					<td>{{solicitud.folio}}</td>
					<td>{{solicitud.a_nombre_de}}</td>
					<td>${{solicitud.importe_numero}}</td>
					<td>{{solicitud.creacion}}</td>
					<td>{%if solicitud.pagado%}Pagado{%else%}Aun no sea pagado{%endif%}</td>
					<td><a href="{%url 'solicitudes:DetailViewSolicitudPropia' solicitud.pk%}">Ver información</a></td>
				</tr>

			{%empty%}

				<tr>
					<td colspan="6">Lista de solicitudes vacia</td>
				</tr>

			{%endfor%}

			</tbody>
		</table>
	</div>
{%endblock content%}
	